### PR TITLE
chore: dependency management improvements 

### PR DESCRIPTION
**Pull request by activars**
Hey, I had to remake a PR, addressing issue #45 :

- Updated build script to use godep managing dependencies
- Updated cli and crypto library using their official github source with commit hash reference in Godeps/Godeps.json
- third_party code is managed by godep, which is now stored in ./Godeps/_workspace 
- ./build and ./test script using the `_workspace` as sandbox, so it doesn't use the global environment (preserves the current build and test behaviour)

### CODE REVIEW

**Comment by yichengq** [comment]
can you save the godep using `godep save -r ./...`?
https://github.com/QubitProducts/etcd-ca/commit/db928c3e8aaf7bd0586013b5431fae03f15a3422#diff-81ede84e0cca11f85752493d8ca5dc57R9
As you see here, it uses external 'github.com/codegangsta/cli' as libraray instead of `.../Godep/...`. This will break if user doesn't have correct external library.

**Comment by activars** [comment]
Not necessary. Conventionally, you need to restore dependencies in development. There are differences between running with `go build` and `godep go build`. Latter command run under a sandbox. You can try it out as the `./build` load dependencies from the `Godeps/_workspace`.

**Comment by activars** [comment]
I tried using `godep save -r ./...`, it seems to having trouble building crypto library.

**Comment by yichengq** [comment]
Let me hand over the follow-ups of the PR.
I think keeping the go standard workflow is a good thing, or it breaks the way for general usage.

**Comment by yichengq** [comment]
BTW, `godep go build` breaks the general `go install`.

**Pull request merged**
