### PR TITLE
Add Dockerfile for building and testing

### PR DESCRIPTION
**Pull request by Nightling**
As the title says. Nothing to see here.

### CODE REVIEW

**Comment by yichengq** [comment]
@Nightling how could i test it? do we need `ADD` and `ENTRYPOINT`?

**Comment by Nightling** [comment]
Running in a container:
`docker run --rm -ti -v /mnt/etcd-ca:/go/src/app/.etcd-ca nightling/etcd-ca app [command]`
Or building:
`docker run --rm -ti -v /mnt/etcd-ca/bin:/go/src/app/bin nightling/etcd-ca ./build`

**Comment by Nightling** [comment]
So I don't think we need an ENTRYPOINT, maybe some pointers in the README.

**Comment by yichengq** [comment]
lgtm. thx for contribution!

**Pull request merged**
