### PR TITLE
chore: adding references to third party dependencies and work naturally with GOPATH

### PR DESCRIPTION
**Pull request by activars**
Hi, this is a chore PR:
- Updated build script to use godep managing dependencies
- Updated `cli` and `crypto` library using their official github source with commit hash reference
- Godeps/Godeps.json should reflect the dependencies
- During development, the project should be cloned into `$GOPATH/src/github.com/coreos/etcd-ca` (you can symbolic-link to a custom project directory to make it easier to work with.)
- After `cd` into the project directory, the existing ./build and ./test script should work

### CODE REVIEW

**Comment by activars** [comment]
This addresses issue #45

**Comment by activars** [comment]
Also, binary in built in both:
 - default go bin path
 - $GOPATH/src/github.com/coreos/etcd-ca/etcd-ca

**Comment by yichengq** [comment]
I am glad to introduce godep into the project, considering it does a good work on dependency.
I don't want to use `godep restore` each time, because it will change the user libraries. Could we use `godep save -r ./...` to save the dependencies inside?

**Comment by activars** [comment]
`godep save -r ./...` would be a good replacement. Do you prefer to commit the dependencies?

When building the dependencies in CI, I usually change `GOPATH` to it's own working directory  so that each build has it's own non-global dependencies.

**Comment by yichengq** [comment]
Yes.

If the user is innocent of this, the command may break his golang dev environemnt. And i think it doesn't hurt us to put it inside the project.

**Comment by activars** [comment]
agree, let me fix this (tomorrow). Thanks for reviewing.

**Pull request closed without merging**
